### ISSUE TITLE
Can't find variable: structuredClone. 

### ISSUE THREAD

**Issue by MeYang901225** [DigiLive/mushroom-strategy#78]
"I encountered the following error after installation: Error loading the dashboard strategy: ReferenceError: Can't find variable: structuredClone. I can open it on the PC and my wife's phone without any issues, but my phone is the only one having problems. What information do I need to provide to identify where the problem is?"

**Comment by DigiLive** [comment]
What phone do you have and which client do you use to access Home Assistant?
Is it the HA Companion App or a certain browser and which versions?

**Comment by MeYang901225** [comment]
"My phone is a 13 Pro, system version 15.1.1. I've tried using mobile browsers including Safari and Chrome, as well as HA Companion, but I'm unable to open it. Here is my HAOS version information: Home Assistant 2023.10.5, Supervisor 2023.10.0, Operating System 11.0, Frontend version: 20231005.0 - latest."
"Just now, I tried to log in using my colleague's Android phone and a web browser, and encountered the following error: Error loading the dashboard strategy
ReferenceError:
structuredClone is not defined."

**Comment by MeYang901225** [comment]
I have tried both manual installation and HACS installation, but I still encounter this error.

**Comment by DigiLive** [comment]
Method `structuredClone` is part of the Web API and since roughly Q1-2022 available in most browsers.
Any browser versions prior to this period are not supported.

You can check the availability of `structuredClone` for you browser [here](https://caniuse.com/?search=structuredClone).
As for the IOS companion, IFAIA it uses a Safari rendering engine.

I think you should update your IOS to at least version 15.4 and your apps to the latest available version.

**Comment by DigiLive** [comment]
@MeYang901225 Any feedback on this?

If not, I'll close the issue soon.
