### ISSUE TITLE
Base Strategies

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#8]
Hi again!
So I was thinking about some ideas for the future of this project and strategies as a whole. 
I think these strategies should be more basic
I think that there should be base strategies that basically tell the basic layout of the views and have customization options
Some examples of a base strategy can be a room subview-based layout or a 1-page room layout etc...
By default, these base strategies use basic built-in cards already present in Home Assistant.  
If users want to define their own cards for a platform, device classes or specific entities they can via options. 
What do you think about this?
I was trying to look for your email but couldn't find it. mine is posted in my GitHub profile.

_Originally posted by @AalianKhan in https://github.com/AalianKhan/mushroom-strategy/issues/6#issuecomment-1498254794_

**Comment by DigiLive** [comment]
I'm not sure what you mean exactly, but you welcome to elaborate here or by email.
Maybe provide an example?

> I was trying to look for your email but couldn't find it. mine is posted in my GitHub profile.

Apparently my address wasn't set to public. It should be visible now.

**Comment by AalianKhan** [comment]
Sorry about that, wrote that comment with very little sleep 😅
So currently the strategy is used to create a dashboard that specifically uses mushroom cards. 

I think it is a good idea to make the strategy more customizable with user-defined cards but retain the same room layout.  
This is already implemented somewhat with `entity_config` option to define custom cards for specific entities. Adding more options, for example, a `platform_config` where a user-defined card is used for a platform instead of a default card. More examples include `room_card_config`, `device_class_config`, etc. This can enable users to create unique dashboards that have the same layout. 

In the first comment, I also expressed the need to move away from mushroom cards and instead use the default cards already installed in Home Assistant to make the strategy more like a foundation and a bit more user-friendly. If the user wants to customize more, then they can edit the YAML for custom definitions of cards as stated earlier. Other base strategies can be made such as a 1-page layout where all rooms and devices are on 1 page, a favourite layout where specific entities are in the first page and other entities are tucked down in other views, etc.

**Comment by ajagnanan** [comment]
Is there a way to exclude (or hide) entities (or maybe the device itself) by ID for a specific dashboard? Hiding is there, but it's a global setting that hides it from other dashboards too.

**Comment by DigiLive** [comment]
> Hiding is there, but it's a global setting that hides it from other dashboards too. 

As far as I know, this is the only build-in method.
To hide an entity from an auto-generated dashboard, such a dashboard has to provide a way to configure the visibility of certain/all entities.

**Comment by ajagnanan** [comment]
Is it possible to add a setting with a list of entity/device ids that get excluded from showing up on the dashboard during the loop?

**Comment by DigiLive** [comment]
I'd say so.

How about creating another issue by means of a feature request?

@AalianKhan Tip:
Somewhere in the repository settings, the owner is able to create issue templates, like bug report and feature request. See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by AalianKhan** [comment]
@ajagnanan Currently there is no such way to hide an entity only for the mushroom strategy dashboard. 
Like DigiLive recommended I recommend opening a separate issue for this where we can discuss it more

Thanks @DigiLive, Just added them

**Comment by DigiLive** [comment]
> Sorry about that, wrote that comment with very little sleep 😅 So currently the strategy is used to create a dashboard that specifically uses mushroom cards.
> 
> I think it is a good idea to make the strategy more customizable with user-defined cards but retain the same room layout. This is already implemented somewhat with `entity_config` option to define custom cards for specific entities. Adding more options, for example, a `platform_config` where a user-defined card is used for a platform instead of a default card. More examples include `room_card_config`, `device_class_config`, etc. This can enable users to create unique dashboards that have the same layout.
> 
> In the first comment, I also expressed the need to move away from mushroom cards and instead use the default cards already installed in Home Assistant to make the strategy more like a foundation and a bit more user-friendly. If the user wants to customize more, then they can edit the YAML for custom definitions of cards as stated earlier. Other base strategies can be made such as a 1-page layout where all rooms and devices are on 1 page, a favourite layout where specific entities are in the first page and other entities are tucked down in other views, etc.

I'm starting to understand what you mean.
In short, I think you don't want a mushroom-strategy, but some kind of a layout strategy.

If so, I'd like to propose smoothing out the current strategy first and move on later.
Don't know about you, but for me, Home Assistant development has quite a steep learning curve.
We can take all of our learned lessons to develop another/improved strategy.

**Comment by AalianKhan** [comment]
Yup, you got it right on.
I totally agree with you. Wanted to give an idea about the future planning for this project
